const attendanceData = {
  records: [
    {
      date_formatted: 'Saturday, june 28, 2026',
      in_time: '9:54 am',
      out_time: '10:05 pm',
      avgTime: '1H 10M',
      working_hours: '1:00',
      type: 'attendance',
    },
    {
      date_formatted: 'Saturday, june 28, 2026',
      in_time: '10:10 am',
      out_time: '10:12 pm',
      avgTime: '0H 2M',
      working_hours: '0:02',
      type: 'attendance',
    },
    {
      date_formatted: 'Sunday, june 29, 2026',
      in_time: '10:54 am',
      out_time: '11:00 pm',
      avgTime: '0H 6M',
      working_hours: '0:06',
      type: 'attendance',
    },
    {
      date_formatted: 'Sunday, june 29, 2026',
      in_time: '10:54 am',
      out_time: '11:00 pm',
      avgTime: '0H 6M',
      working_hours: '0:06',
      type: 'attendance',
    },
    {
      date_formatted: 'Monday, june 30, 2026',
      in_time: '11:20 am',
      out_time: '11:30 pm',
      avgTime: '0H 10M',
      working_hours: '0:10',
      type: 'attendance',
    },
    {
      date_formatted: 'Monday, june 30, 2026',
      in_time: '11:30 am',
      out_time: '11:40 pm',
      avgTime: '0H 10M',
      working_hours: '0:10',
      type: 'attendance',
    },
    {
      date_formatted: 'Tuesday, june 30, 2026',
      in_time: '8:54 am',
      out_time: '6:05 pm',
      avgTime: '9H 10M',
      working_hours: '9:00',
      type: 'attendance',
    },
  ],
};
export default attendanceData;
