export default {
    appTitle: 'My Attendance',
    splash: {},
    preLogin: {
        title: 'Choose Mode',
        title_host: 'Continue as doctor',
        title_client: 'Continue as patient',
        welcome: 'Welcome to smart doctor',
    },
    login: {
        app_name: 'My Attendance',
        pass_required_validation: 'Please enter your account password.',
        min_pass_validation: 'Password cannot be less than eight characters.',
        email_required_validation: 'Please enter your email address.',
        pass_validation: 'Password must be of at least 8 characters.',
        enter_valid_email_validation: 'Please enter a valid email address.',
        email_address: 'Email Address',
        enter_your_email: 'Please type your email address',
        password: 'Password',
        enter_pass: 'Please type your password',
        sign_in: 'Sign In',
        label_remember_me: 'Remember Me',
        title: 'Login',
        not_member_signup_now: 'Not a member? Sign up now',
        register: 'or register?',
        subtitle: 'Already a member? Sign in to your account',
        forgot_password: 'Forgot Password?',
    },
    create_team: {
        title: 'Create Team',
        sumbit: 'Submit',
        team_name: 'Team Name',
        enter_team_name: 'Workplace or School name',
        team_name_validation: 'Please enter a valid workplace.',
        full_name: 'Full Name',
        enter_full_name: 'Enter your full name',
        full_name_validation: 'Please enter a valid name.',
        email: 'Email Address',
        enter_your_email: 'Enter your email address',
        email_validation: 'Please enter your email address.',
        enter_valid_email_validation: 'Please enter a valid email address',
        password: 'Password',
        create_password: 'Create a new password',
        pass_required_validation: 'Please enter your account password.',
        min_pass_validation: 'Password cannot be less than eight characters.',
        privacy_text: 'By tapping, you agree to',
        privacy_policy: ' Privacy Policy ',
        and: 'and',
        terms_of_service: ' Terms of Service',
    },
    common: {
        no_record_found: 'No record found',
        not_found: 'Not found',
        some_thing_bad_happened:
            'Something bad happened, please try again later',
        try_again: 'Try again',
        name_valid: 'Only alphabets are allowed',
    },
    forgotPassword: {
        title: 'Forgot Password',
        description:
            'Please enter your email address where you will recieve instructions to reset your password.',
        email_placeholder: 'Enter your email address',
        btn_text: 'Reset Password',
        dialog_heading: 'Forgot Password',
        dialogue_text:
            'An email containing information on how to reset your password has been send to',
    },
    home: {
        attendance: {
            title: 'Attendance',
        },
        punchInAndOut: {},
        requests: {
            title: 'Requests',
            no_record_found: "You haven't created any request yet",
        },
    },
    faq: {
        title: 'Help',
        contactUs: 'Contact us',
        faq: 'FREQUENTLY ASKED QUESTIONS',
        faqDetail: 'FAQ Details',
    },
    puchInAndOut: {
        punch_in: 'Punch In',
        punch_out: 'Punch Out',
        qoute: 'QUOTE OF THE DAY',
        signout: 'Signout',
        signout_text: 'Are you sure you want to signout?',
        save_photo: 'Save Photo',
        save_picture: 'Are you sure? You want to save in photo library',
        cancel: 'Cancel',
        confirm: 'Yes, Confirm',
        set_as_picture: 'Set as Profile Picture',
        please_enable_device_location: 'Please enable device location',
        title_permission: 'Storage Permission',
        subtext_permissions:
            'MyAttendance needs access to your storage to download Photos.',
        btntext_permission: 'Allow',
        saveDiaglog: 'Image saved to gallery',
        location_alert: 'Location Alert',
        it_seems_you_are_out: 'It seems like you are outside of',
        are_you_sure_punchin: 'location. Are you sure you want to proceed?',
        location_desc:
            'It seems like you are outside of placeHolderName location.Are you sure you want to punch in?',
        punch_out_greater_than_punch_desc:
            'Punch out time must be greater than punched in time',
        same_day_desc: 'Punch Out time must be on the same day',
    },

    newLeave: {
        title: 'New Leave Request',
        submit: 'Submit',
        leave_type: 'LEAVE TYPE',
        select_leave_type: 'Select leave type',
        half_day: 'HALF DAY',
        start_date: 'START DATE',
        select_start_date: 'Select Start Date',
        end_date: 'END DATE',
        select_end_date: 'Select End Date',
        reason: 'REASON',
        message: 'Start typing leave reason',
        leave_type_validation: 'Please select a leave type',
        start_date_validation: 'Please select a start date',
        end_date_validation: 'Please select a end date',
        request_dialogbox: 'Request has been submitted',
    },
    contactUs: {
        title: 'Contact us',
        btn_text: 'Send',
        message_placeholder: 'Start typing your message...',
        desc: "Didn't find an answer to your question in the FAQ? Type in your query and we will get back to you shortly through email.",
        errorMessage: 'Please type your message',
    },
    reportAndTools: {
        title: 'Reports & Admin Tools',
        topMessage:
            'You can use the following link to log in to ittendance client portal from your laptop,',
        link: 'https://www.ittendance.com/panel/signin',
        desc: 'ittendance client portal offers,',
        offers: '\u25CF   Detail Reporting\n\u25CF   Invite users/team members\n\u25CF   Leaves approval & management\n\u25CF   Setting & modifications\n\u25CF   Bulk punch in/out and much more',
        buttonTitle: 'Start using ittendance',
    },
    welcome: {
        title: 'Welcome to ittendance',
        skip: 'Skip',
        message:
            'Please watch the introduction video to learn how ittendance works.',
        buttonTitle: 'Continue',
    },
    accountVerification: {
        title: 'Verification Code',
        code_required_validation: 'Please enter your given code.',
        confirmation_code:
            'Enter the confirmation code here which we have sent you on your',
        not_receive_code: "Haven't received confirmation code yet? ",
        resend_code: 'Resend Code',
        verification_code: 'Verification Code',
        verification_code_placeholder: 'Enter verification code',
    },
}
