-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgcDMWYvxdLVUsaSMR
OljpJ/j2aHWlvlXYLGW+dh0P+pWgCgYIKoZIzj0DAQehRANCAATu+6IoKOvzz46A
FhFLl4gjglk46DCD2eLzbSGD/2gY5qkZqbbw0TikB6nL3h8jqT6JDFznzUTwMwMp
RmvYJlHQ
-----END PRIVATE KEY-----